/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.awt.BorderLayout;

/**
 *
 * @author alulab14
 */
public class Vcliente_inscribirClase extends javax.swing.JPanel {

    /**
     * Creates new form Vcliente_inscribirClase
     */
    public Vcliente_inscribirClase() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelFondo = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblClases = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        ftfFecFin = new javax.swing.JFormattedTextField();
        jLabel7 = new javax.swing.JLabel();
        ftfHorIni = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        txtDescClase = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtDuracion = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        ftfHorFin = new javax.swing.JFormattedTextField();
        jLabel9 = new javax.swing.JLabel();
        txtNombEntrenador = new javax.swing.JTextField();
        txtCap = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtVac = new javax.swing.JTextField();
        ftfFecIni = new javax.swing.JFormattedTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        listClasesInscritas = new javax.swing.JList<>();
        btnInscribirClase = new javax.swing.JButton();
        btnRetirarClase = new javax.swing.JButton();

        setBackground(new java.awt.Color(117, 126, 131));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelFondo.setBackground(new java.awt.Color(117, 126, 131));

        jPanel1.setBackground(new java.awt.Color(50, 54, 56));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(178, 197, 204));
        jLabel1.setText("CLASES DISPONIBLES");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tblClases.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Descripción de Clase", "Entrenador", "Capacidad", "Vacantes", "Fecha Inicio"
            }
        ));
        tblClases.setGridColor(new java.awt.Color(178, 197, 204));
        tblClases.setSelectionBackground(new java.awt.Color(178, 197, 204));
        tblClases.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(tblClases);
        if (tblClases.getColumnModel().getColumnCount() > 0) {
            tblClases.getColumnModel().getColumn(0).setMinWidth(200);
            tblClases.getColumnModel().getColumn(0).setPreferredWidth(200);
            tblClases.getColumnModel().getColumn(0).setMaxWidth(200);
            tblClases.getColumnModel().getColumn(2).setMinWidth(60);
            tblClases.getColumnModel().getColumn(2).setPreferredWidth(60);
            tblClases.getColumnModel().getColumn(2).setMaxWidth(60);
            tblClases.getColumnModel().getColumn(3).setMinWidth(60);
            tblClases.getColumnModel().getColumn(3).setPreferredWidth(60);
            tblClases.getColumnModel().getColumn(3).setMaxWidth(60);
        }

        jPanel2.setBackground(new java.awt.Color(50, 54, 56));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(178, 197, 204));
        jLabel2.setText("CLASE SELECCIONADA");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(178, 197, 204));
        jLabel12.setText("CLASES INSCRITAS");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addGap(29, 29, 29))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel12))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(117, 126, 131));

        ftfFecFin.setEditable(false);
        ftfFecFin.setBackground(new java.awt.Color(117, 126, 131));
        ftfFecFin.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(200, 149, 90)));
        ftfFecFin.setForeground(new java.awt.Color(240, 240, 240));
        ftfFecFin.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));
        ftfFecFin.setToolTipText("DD/MM/AAAA");
        ftfFecFin.setSelectionColor(new java.awt.Color(178, 197, 204));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(178, 197, 204));
        jLabel7.setText("Hora Inicio: ");

        ftfHorIni.setEditable(false);
        ftfHorIni.setBackground(new java.awt.Color(117, 126, 131));
        ftfHorIni.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(200, 149, 90)));
        ftfHorIni.setForeground(new java.awt.Color(240, 240, 240));
        ftfHorIni.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getTimeInstance(java.text.DateFormat.SHORT))));
        ftfHorIni.setToolTipText("HH:MM (AM/PM)");
        ftfHorIni.setSelectionColor(new java.awt.Color(178, 197, 204));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(178, 197, 204));
        jLabel3.setText("Descripción de la Clase: ");

        txtDescClase.setEditable(false);
        txtDescClase.setBackground(new java.awt.Color(117, 126, 131));
        txtDescClase.setForeground(new java.awt.Color(240, 240, 240));
        txtDescClase.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(200, 149, 90)));
        txtDescClase.setSelectionColor(new java.awt.Color(178, 197, 204));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(178, 197, 204));
        jLabel4.setText("Entrenador: ");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(178, 197, 204));
        jLabel10.setText("Vacantes: ");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(178, 197, 204));
        jLabel8.setText("Hora Fin: ");

        txtDuracion.setEditable(false);
        txtDuracion.setBackground(new java.awt.Color(117, 126, 131));
        txtDuracion.setForeground(new java.awt.Color(240, 240, 240));
        txtDuracion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(200, 149, 90)));
        txtDuracion.setSelectionColor(new java.awt.Color(178, 197, 204));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(178, 197, 204));
        jLabel6.setText("Fecha Fin: ");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(178, 197, 204));
        jLabel11.setText("Duración: ");

        ftfHorFin.setEditable(false);
        ftfHorFin.setBackground(new java.awt.Color(117, 126, 131));
        ftfHorFin.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(200, 149, 90)));
        ftfHorFin.setForeground(new java.awt.Color(240, 240, 240));
        ftfHorFin.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getTimeInstance(java.text.DateFormat.SHORT))));
        ftfHorFin.setToolTipText("HH:MM (AM/PM)");
        ftfHorFin.setSelectionColor(new java.awt.Color(178, 197, 204));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(178, 197, 204));
        jLabel9.setText("Capacidad: ");

        txtNombEntrenador.setEditable(false);
        txtNombEntrenador.setBackground(new java.awt.Color(117, 126, 131));
        txtNombEntrenador.setForeground(new java.awt.Color(240, 240, 240));
        txtNombEntrenador.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(200, 149, 90)));
        txtNombEntrenador.setSelectionColor(new java.awt.Color(178, 197, 204));

        txtCap.setEditable(false);
        txtCap.setBackground(new java.awt.Color(117, 126, 131));
        txtCap.setForeground(new java.awt.Color(240, 240, 240));
        txtCap.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(200, 149, 90)));
        txtCap.setSelectionColor(new java.awt.Color(178, 197, 204));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(178, 197, 204));
        jLabel5.setText("Fecha Inicio: ");

        txtVac.setEditable(false);
        txtVac.setBackground(new java.awt.Color(117, 126, 131));
        txtVac.setForeground(new java.awt.Color(240, 240, 240));
        txtVac.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(200, 149, 90)));
        txtVac.setSelectionColor(new java.awt.Color(178, 197, 204));

        ftfFecIni.setEditable(false);
        ftfFecIni.setBackground(new java.awt.Color(117, 126, 131));
        ftfFecIni.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(200, 149, 90)));
        ftfFecIni.setForeground(new java.awt.Color(240, 240, 240));
        ftfFecIni.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));
        ftfFecIni.setToolTipText("DD/MM/AAAA");
        ftfFecIni.setSelectionColor(new java.awt.Color(178, 197, 204));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ftfHorIni, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel9))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel11)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtDuracion, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addGap(18, 18, 18)
                                        .addComponent(ftfHorFin, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel10)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCap, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtVac, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(311, 311, 311))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtDescClase, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addGap(29, 29, 29)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtNombEntrenador, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                                    .addComponent(ftfFecFin)
                                    .addComponent(ftfFecIni))))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDescClase, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtNombEntrenador, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(ftfFecIni, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(ftfFecFin, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(ftfHorIni, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(txtCap, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtVac, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(ftfHorFin, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDuracion, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(48, 48, 48))
        );

        listClasesInscritas.setBackground(new java.awt.Color(178, 197, 204));
        listClasesInscritas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(200, 149, 90)));
        listClasesInscritas.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        listClasesInscritas.setForeground(new java.awt.Color(240, 240, 240));
        listClasesInscritas.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        listClasesInscritas.setSelectionBackground(new java.awt.Color(200, 149, 90));
        listClasesInscritas.setSelectionForeground(new java.awt.Color(240, 240, 240));
        jScrollPane2.setViewportView(listClasesInscritas);

        btnInscribirClase.setBackground(new java.awt.Color(50, 54, 56));
        btnInscribirClase.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnInscribirClase.setForeground(new java.awt.Color(178, 197, 204));
        btnInscribirClase.setText("Inscribir");
        btnInscribirClase.setBorder(null);
        btnInscribirClase.setBorderPainted(false);
        btnInscribirClase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInscribirClaseActionPerformed(evt);
            }
        });

        btnRetirarClase.setBackground(new java.awt.Color(50, 54, 56));
        btnRetirarClase.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnRetirarClase.setForeground(new java.awt.Color(178, 197, 204));
        btnRetirarClase.setText("Retirar");
        btnRetirarClase.setBorder(null);
        btnRetirarClase.setBorderPainted(false);
        btnRetirarClase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetirarClaseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelFondoLayout = new javax.swing.GroupLayout(panelFondo);
        panelFondo.setLayout(panelFondoLayout);
        panelFondoLayout.setHorizontalGroup(
            panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelFondoLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 568, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 23, Short.MAX_VALUE))
            .addGroup(panelFondoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelFondoLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelFondoLayout.createSequentialGroup()
                        .addComponent(btnRetirarClase, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnInscribirClase, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34))))
        );
        panelFondoLayout.setVerticalGroup(
            panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFondoLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelFondoLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnInscribirClase, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnRetirarClase, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelFondoLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 24, Short.MAX_VALUE))))
        );

        add(panelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 490));
    }// </editor-fold>//GEN-END:initComponents

    private void btnInscribirClaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInscribirClaseActionPerformed

    }//GEN-LAST:event_btnInscribirClaseActionPerformed

    private void btnRetirarClaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetirarClaseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRetirarClaseActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInscribirClase;
    private javax.swing.JButton btnRetirarClase;
    private javax.swing.JFormattedTextField ftfFecFin;
    private javax.swing.JFormattedTextField ftfFecIni;
    private javax.swing.JFormattedTextField ftfHorFin;
    private javax.swing.JFormattedTextField ftfHorIni;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> listClasesInscritas;
    private javax.swing.JPanel panelFondo;
    private javax.swing.JTable tblClases;
    private javax.swing.JTextField txtCap;
    private javax.swing.JTextField txtDescClase;
    private javax.swing.JTextField txtDuracion;
    private javax.swing.JTextField txtNombEntrenador;
    private javax.swing.JTextField txtVac;
    // End of variables declaration//GEN-END:variables
}
