/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.awt.Color;
import javax.swing.JButton;

/**
 *
 * @author alulab14
 */
public class Vcliente_ProductosComprados extends javax.swing.JPanel {

    /**
     * Creates new form VclienteProductosComprados
     */
    public Vcliente_ProductosComprados() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelFondo = new javax.swing.JPanel();
        btnHistorialProd = new javax.swing.JButton();
        btnProdMas = new javax.swing.JButton();
        ckbFiltFec = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        dcFecIni = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        dcFecFin = new com.toedter.calendar.JDateChooser();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProductos = new javax.swing.JTable();

        setBackground(new java.awt.Color(117, 126, 131));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelFondo.setBackground(new java.awt.Color(117, 126, 131));

        btnHistorialProd.setBackground(new java.awt.Color(50, 54, 56));
        btnHistorialProd.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnHistorialProd.setForeground(new java.awt.Color(178, 197, 204));
        btnHistorialProd.setText("HISTORIAL DE PRODUCTOS COMPRADOS");
        btnHistorialProd.setBorder(null);
        btnHistorialProd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHistorialProdMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnHistorialProdMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnHistorialProdMouseExited(evt);
            }
        });
        btnHistorialProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHistorialProdActionPerformed(evt);
            }
        });

        btnProdMas.setBackground(new java.awt.Color(50, 54, 56));
        btnProdMas.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnProdMas.setForeground(new java.awt.Color(178, 197, 204));
        btnProdMas.setText("PRODUCTOS MÁS COMPRADOS");
        btnProdMas.setBorder(null);
        btnProdMas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnProdMasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnProdMasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnProdMasMouseExited(evt);
            }
        });
        btnProdMas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProdMasActionPerformed(evt);
            }
        });

        ckbFiltFec.setBackground(new java.awt.Color(117, 126, 131));
        ckbFiltFec.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ckbFiltFec.setForeground(new java.awt.Color(240, 240, 240));
        ckbFiltFec.setText("Filtrar por fecha");
        ckbFiltFec.setBorder(null);
        ckbFiltFec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckbFiltFecActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(178, 197, 204));
        jLabel1.setText("Desde: ");

        dcFecIni.setEnabled(false);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(178, 197, 204));
        jLabel2.setText("Hasta: ");

        dcFecFin.setEnabled(false);

        jPanel1.setBackground(new java.awt.Color(50, 54, 56));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(178, 197, 204));
        jLabel3.setText("PRODUCTOS COMPRADOS");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(415, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tblProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblProductos.setEnabled(false);
        tblProductos.setGridColor(new java.awt.Color(200, 189, 187));
        tblProductos.setSelectionBackground(new java.awt.Color(178, 197, 204));
        tblProductos.setSelectionForeground(new java.awt.Color(240, 240, 240));
        jScrollPane1.setViewportView(tblProductos);

        javax.swing.GroupLayout panelFondoLayout = new javax.swing.GroupLayout(panelFondo);
        panelFondo.setLayout(panelFondoLayout);
        panelFondoLayout.setHorizontalGroup(
            panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelFondoLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(panelFondoLayout.createSequentialGroup()
                        .addComponent(btnHistorialProd, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnProdMas, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelFondoLayout.createSequentialGroup()
                        .addComponent(ckbFiltFec)
                        .addGap(41, 41, 41)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(dcFecIni, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(dcFecFin, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelFondoLayout.setVerticalGroup(
            panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFondoLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel2)
                        .addComponent(dcFecFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(dcFecIni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ckbFiltFec)
                            .addComponent(jLabel1))))
                .addGap(18, 18, 18)
                .addGroup(panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnProdMas, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHistorialProd, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        add(panelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnProdMasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProdMasActionPerformed
        setbtnColor(btnProdMas);
        resetbtnColor(btnHistorialProd);
        tblProductos.setEnabled(true);
    }//GEN-LAST:event_btnProdMasActionPerformed

    private void btnHistorialProdMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHistorialProdMouseEntered
        //setbtnColor(btnHistorialProd);
    }//GEN-LAST:event_btnHistorialProdMouseEntered

    private void btnHistorialProdMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHistorialProdMouseExited
        //resetbtnColor(btnHistorialProd);
    }//GEN-LAST:event_btnHistorialProdMouseExited

    private void btnProdMasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProdMasMouseEntered
        //setbtnColor(btnProdMas);
    }//GEN-LAST:event_btnProdMasMouseEntered

    private void btnProdMasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProdMasMouseExited
        //resetbtnColor(btnProdMas);
    }//GEN-LAST:event_btnProdMasMouseExited

    private void btnHistorialProdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHistorialProdMouseClicked
        
    }//GEN-LAST:event_btnHistorialProdMouseClicked

    private void btnProdMasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProdMasMouseClicked
        
    }//GEN-LAST:event_btnProdMasMouseClicked

    private void btnHistorialProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHistorialProdActionPerformed
        setbtnColor(btnHistorialProd);
        resetbtnColor(btnProdMas);
        tblProductos.setEnabled(true);
    }//GEN-LAST:event_btnHistorialProdActionPerformed

    private void ckbFiltFecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckbFiltFecActionPerformed
        if(ckbFiltFec.isSelected()){
            dcFecIni.setEnabled(true);
            dcFecFin.setEnabled(true);
            tblProductos.setEnabled(true);
        }else{
            dcFecIni.setEnabled(false);
            dcFecFin.setEnabled(false);
            tblProductos.setEnabled(false);
        }
    }//GEN-LAST:event_ckbFiltFecActionPerformed

    public void setbtnColor(JButton btn){
        btn.setContentAreaFilled(true);
        btn.setForeground(new Color(50,54,56));
        btn.setBackground(new Color(178,197,204));
    }
    
    public void resetbtnColor(JButton btn){
        btn.setContentAreaFilled(true);
        btn.setForeground(new Color(178,197,204));
        btn.setBackground(new Color(50,54,56));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHistorialProd;
    private javax.swing.JButton btnProdMas;
    private javax.swing.JCheckBox ckbFiltFec;
    private com.toedter.calendar.JDateChooser dcFecFin;
    private com.toedter.calendar.JDateChooser dcFecIni;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panelFondo;
    private javax.swing.JTable tblProductos;
    // End of variables declaration//GEN-END:variables
}
