/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.awt.BorderLayout;
import java.awt.Color;

/**
 *
 * @author alulab14
 */
public class Vcliente_perfil extends javax.swing.JPanel {

    /**
     * Creates new form Vcliente_perfil
     */
    public Vcliente_perfil() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelFondo = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtApMat = new javax.swing.JTextField();
        txtFecNac = new javax.swing.JTextField();
        txtNomb = new javax.swing.JTextField();
        txtApPat = new javax.swing.JTextField();
        txtDNI = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        txtTel = new javax.swing.JTextField();
        txtDistrito = new javax.swing.JTextField();
        txtDireccion = new javax.swing.JTextField();
        btnModPerfil = new javax.swing.JButton();

        setBackground(new java.awt.Color(117, 126, 131));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelFondo.setBackground(new java.awt.Color(117, 126, 131));

        jPanel2.setBackground(new java.awt.Color(117, 126, 131));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos Personales", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(178, 197, 204))); // NOI18N
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(178, 197, 204));
        jLabel5.setText("DNI:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(178, 197, 204));
        jLabel6.setText("Nombres: ");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(178, 197, 204));
        jLabel7.setText("Apellido Paterno: ");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(178, 197, 204));
        jLabel8.setText("Apellido Materno: ");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(178, 197, 204));
        jLabel9.setText("Fecha Nacimiento: ");

        txtApMat.setEditable(false);
        txtApMat.setBackground(new java.awt.Color(117, 126, 131));
        txtApMat.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtApMat.setForeground(new java.awt.Color(240, 240, 240));
        txtApMat.setText("XXXX-XXXX-XXXX-XXXX");
        txtApMat.setBorder(null);
        txtApMat.setSelectedTextColor(new java.awt.Color(253, 255, 246));
        txtApMat.setSelectionColor(new java.awt.Color(178, 197, 204));

        txtFecNac.setEditable(false);
        txtFecNac.setBackground(new java.awt.Color(117, 126, 131));
        txtFecNac.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtFecNac.setForeground(new java.awt.Color(240, 240, 240));
        txtFecNac.setText("XXXX-XXXX-XXXX-XXXX");
        txtFecNac.setBorder(null);
        txtFecNac.setSelectedTextColor(new java.awt.Color(253, 255, 246));
        txtFecNac.setSelectionColor(new java.awt.Color(178, 197, 204));

        txtNomb.setEditable(false);
        txtNomb.setBackground(new java.awt.Color(117, 126, 131));
        txtNomb.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtNomb.setForeground(new java.awt.Color(240, 240, 240));
        txtNomb.setText("XXXX-XXXX-XXXX-XXXX");
        txtNomb.setBorder(null);
        txtNomb.setSelectedTextColor(new java.awt.Color(253, 255, 246));
        txtNomb.setSelectionColor(new java.awt.Color(178, 197, 204));

        txtApPat.setEditable(false);
        txtApPat.setBackground(new java.awt.Color(117, 126, 131));
        txtApPat.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtApPat.setForeground(new java.awt.Color(240, 240, 240));
        txtApPat.setText("XXXX-XXXX-XXXX-XXXX");
        txtApPat.setBorder(null);
        txtApPat.setSelectedTextColor(new java.awt.Color(253, 255, 246));
        txtApPat.setSelectionColor(new java.awt.Color(178, 197, 204));

        txtDNI.setEditable(false);
        txtDNI.setBackground(new java.awt.Color(117, 126, 131));
        txtDNI.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtDNI.setForeground(new java.awt.Color(240, 240, 240));
        txtDNI.setText("12345678");
        txtDNI.setBorder(null);
        txtDNI.setSelectedTextColor(new java.awt.Color(253, 255, 246));
        txtDNI.setSelectionColor(new java.awt.Color(178, 197, 204));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(178, 197, 204));
        jLabel10.setText("Dirección: ");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(178, 197, 204));
        jLabel11.setText("Distrito: ");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(178, 197, 204));
        jLabel12.setText("Teléfono: ");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(178, 197, 204));
        jLabel13.setText("E-mail: ");

        txtEmail.setEditable(false);
        txtEmail.setBackground(new java.awt.Color(117, 126, 131));
        txtEmail.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtEmail.setForeground(new java.awt.Color(240, 240, 240));
        txtEmail.setText("XXXX-XXXX-XXXX-XXXX");
        txtEmail.setBorder(null);
        txtEmail.setSelectedTextColor(new java.awt.Color(253, 255, 246));
        txtEmail.setSelectionColor(new java.awt.Color(178, 197, 204));

        txtTel.setEditable(false);
        txtTel.setBackground(new java.awt.Color(117, 126, 131));
        txtTel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtTel.setForeground(new java.awt.Color(240, 240, 240));
        txtTel.setText("XXXX-XXXX-XXXX-XXXX");
        txtTel.setBorder(null);
        txtTel.setSelectedTextColor(new java.awt.Color(253, 255, 246));
        txtTel.setSelectionColor(new java.awt.Color(178, 197, 204));

        txtDistrito.setEditable(false);
        txtDistrito.setBackground(new java.awt.Color(117, 126, 131));
        txtDistrito.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtDistrito.setForeground(new java.awt.Color(240, 240, 240));
        txtDistrito.setText("XXXX-XXXX-XXXX-XXXX");
        txtDistrito.setBorder(null);
        txtDistrito.setSelectedTextColor(new java.awt.Color(253, 255, 246));
        txtDistrito.setSelectionColor(new java.awt.Color(178, 197, 204));

        txtDireccion.setEditable(false);
        txtDireccion.setBackground(new java.awt.Color(117, 126, 131));
        txtDireccion.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtDireccion.setForeground(new java.awt.Color(240, 240, 240));
        txtDireccion.setText("XXXX-XXXX-XXXX-XXXX");
        txtDireccion.setBorder(null);
        txtDireccion.setSelectedTextColor(new java.awt.Color(253, 255, 246));
        txtDireccion.setSelectionColor(new java.awt.Color(178, 197, 204));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(105, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel13)
                    .addComponent(jLabel11)
                    .addComponent(jLabel9)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(jLabel8)
                    .addComponent(jLabel10)
                    .addComponent(jLabel12))
                .addGap(62, 62, 62)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtApPat, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNomb, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDNI, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtApMat, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(txtFecNac, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtDireccion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtDistrito, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEmail, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtDNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtNomb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtApPat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtApMat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtFecNac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtDistrito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtTel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(52, Short.MAX_VALUE))
        );

        btnModPerfil.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnModPerfil.setForeground(new java.awt.Color(178, 197, 204));
        btnModPerfil.setText("<html><u>Modificar Perfil</u><html>");
        btnModPerfil.setBorder(null);
        btnModPerfil.setContentAreaFilled(false);
        btnModPerfil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnModPerfilMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnModPerfilMouseReleased(evt);
            }
        });
        btnModPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModPerfilActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelFondoLayout = new javax.swing.GroupLayout(panelFondo);
        panelFondo.setLayout(panelFondoLayout);
        panelFondoLayout.setHorizontalGroup(
            panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFondoLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnModPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        panelFondoLayout.setVerticalGroup(
            panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFondoLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnModPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        add(panelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 490));
    }// </editor-fold>//GEN-END:initComponents

    private void btnModPerfilMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnModPerfilMousePressed
        btnModPerfil.setForeground(new Color(50,54,56));
    }//GEN-LAST:event_btnModPerfilMousePressed

    private void btnModPerfilMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnModPerfilMouseReleased
        btnModPerfil.setForeground(new Color(178,197,204));
    }//GEN-LAST:event_btnModPerfilMouseReleased

    private void btnModPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModPerfilActionPerformed
        Vcliente_modPerfil ventModPerfil = new Vcliente_modPerfil();
        ventModPerfil.setSize(610,490);
        ventModPerfil.setLocation(0, 0);

        panelFondo.removeAll();
        panelFondo.add(ventModPerfil, BorderLayout.CENTER);
        panelFondo.revalidate();
        panelFondo.repaint();
    }//GEN-LAST:event_btnModPerfilActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnModPerfil;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel panelFondo;
    private javax.swing.JTextField txtApMat;
    private javax.swing.JTextField txtApPat;
    private javax.swing.JTextField txtDNI;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtDistrito;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFecNac;
    private javax.swing.JTextField txtNomb;
    private javax.swing.JTextField txtTel;
    // End of variables declaration//GEN-END:variables
}
