/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;


import dao.CursoDAO;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.table.TableModel;
import modelo.Clase;
import modelo.Curso;

/**
 *
 * @author Lin
 */
public class Ventrenador_addClase extends javax.swing.JPanel {

    /**
     * Creates new form Ventrenador_addClase
     */
    ArrayList<Curso>listaCursos;
    CursoDAO cursoDao=new CursoDAO();
    public Ventrenador_addClase() {
        initComponents();
        /*TableModel modelCursos=tblCursos.getModel();
        listaCursos=cursoDao.readAll();
        for(int i=0;i<listaCursos.size();i++){
            modelCursos.setValueAt(listaCursos.get(i).getId(), i, 0);
            modelCursos.setValueAt(listaCursos.get(i).getNombre(), i, 1);
            modelCursos.setValueAt(listaCursos.get(i).getDescripcion(), i, 2);
        }*/
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelFondo = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCursos = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtIDCurso = new javax.swing.JTextField();
        txtNombCurso = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        txtDescClase = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        ftfFecIni = new javax.swing.JFormattedTextField();
        ftfFecFin = new javax.swing.JFormattedTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        ftfHorIni = new javax.swing.JFormattedTextField();
        ftfHorFin = new javax.swing.JFormattedTextField();
        jLabel12 = new javax.swing.JLabel();
        txtDuracion = new javax.swing.JTextField();
        spinCap = new javax.swing.JSpinner();
        jLabel13 = new javax.swing.JLabel();
        cbxDisp = new javax.swing.JComboBox<>();
        btnAgregarClase = new javax.swing.JButton();

        setBackground(new java.awt.Color(85, 123, 131));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelFondo.setBackground(new java.awt.Color(85, 123, 131));

        tblCursos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID Curso", "Nombre Curso", "Descripción", "Clases Dictadas"
            }
        ));
        tblCursos.setGridColor(new java.awt.Color(162, 213, 171));
        tblCursos.setSelectionBackground(new java.awt.Color(57, 174, 169));
        tblCursos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(tblCursos);

        jPanel2.setBackground(new java.awt.Color(32, 101, 98));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(229, 239, 193));
        jLabel4.setText("CURSOS DISPONIBLES");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(437, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(32, 101, 98));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(229, 239, 193));
        jLabel2.setText("CURSO SELECCIONADO");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(431, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(32, 101, 98));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(229, 239, 193));
        jLabel1.setText("DATOS DE CLASE A AGREGAR");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(391, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(85, 123, 131));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(229, 239, 193));
        jLabel5.setText("ID Curso: ");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(229, 239, 193));
        jLabel3.setText("Nombre del Curso: ");

        txtIDCurso.setEditable(false);
        txtIDCurso.setBackground(new java.awt.Color(85, 123, 131));
        txtIDCurso.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtIDCurso.setForeground(new java.awt.Color(229, 239, 193));
        txtIDCurso.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(57, 174, 169)));
        txtIDCurso.setSelectedTextColor(new java.awt.Color(253, 255, 246));
        txtIDCurso.setSelectionColor(new java.awt.Color(57, 174, 169));

        txtNombCurso.setEditable(false);
        txtNombCurso.setBackground(new java.awt.Color(85, 123, 131));
        txtNombCurso.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtNombCurso.setForeground(new java.awt.Color(229, 239, 193));
        txtNombCurso.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(57, 174, 169)));
        txtNombCurso.setSelectedTextColor(new java.awt.Color(253, 255, 246));
        txtNombCurso.setSelectionColor(new java.awt.Color(57, 174, 169));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(txtIDCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(txtNombCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtNombCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtIDCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5)))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(85, 123, 131));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(229, 239, 193));
        jLabel6.setText("Descripción de la clase: ");

        txtDescClase.setBackground(new java.awt.Color(229, 239, 193));
        txtDescClase.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtDescClase.setForeground(new java.awt.Color(91, 81, 81));
        txtDescClase.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(57, 174, 169)));
        txtDescClase.setSelectedTextColor(new java.awt.Color(253, 255, 246));
        txtDescClase.setSelectionColor(new java.awt.Color(57, 174, 169));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(229, 239, 193));
        jLabel7.setText("Capacidad: ");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(229, 239, 193));
        jLabel8.setText("Fecha Inicio: ");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(229, 239, 193));
        jLabel9.setText("Fecha Fin: ");

        ftfFecIni.setBackground(new java.awt.Color(229, 239, 193));
        ftfFecIni.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(57, 174, 169)));
        ftfFecIni.setForeground(new java.awt.Color(91, 81, 81));
        ftfFecIni.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));
        ftfFecIni.setText("DD/MM/AAAA");
        ftfFecIni.setToolTipText("dd/mm/aaaa");
        ftfFecIni.setSelectedTextColor(new java.awt.Color(253, 255, 246));
        ftfFecIni.setSelectionColor(new java.awt.Color(57, 174, 169));
        ftfFecIni.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ftfFecIniMouseClicked(evt);
            }
        });
        ftfFecIni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ftfFecIniActionPerformed(evt);
            }
        });

        ftfFecFin.setBackground(new java.awt.Color(229, 239, 193));
        ftfFecFin.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(57, 174, 169)));
        ftfFecFin.setForeground(new java.awt.Color(91, 81, 81));
        ftfFecFin.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));
        ftfFecFin.setText("DD/MM/AAAA");
        ftfFecFin.setToolTipText("dd/mm/aaaa");
        ftfFecFin.setSelectedTextColor(new java.awt.Color(253, 255, 246));
        ftfFecFin.setSelectionColor(new java.awt.Color(57, 174, 169));
        ftfFecFin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ftfFecFinMouseClicked(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(229, 239, 193));
        jLabel10.setText("Hora Fin: ");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(229, 239, 193));
        jLabel11.setText("Hora Inicio: ");

        ftfHorIni.setBackground(new java.awt.Color(229, 239, 193));
        ftfHorIni.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(57, 174, 169)));
        ftfHorIni.setForeground(new java.awt.Color(91, 81, 81));
        ftfHorIni.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getTimeInstance(java.text.DateFormat.SHORT))));
        ftfHorIni.setText("HH:MM (AM/PM)");
        ftfHorIni.setToolTipText("HH:MM en AM/PM");
        ftfHorIni.setSelectedTextColor(new java.awt.Color(253, 255, 246));
        ftfHorIni.setSelectionColor(new java.awt.Color(57, 174, 169));
        ftfHorIni.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ftfHorIniMouseClicked(evt);
            }
        });

        ftfHorFin.setBackground(new java.awt.Color(229, 239, 193));
        ftfHorFin.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(57, 174, 169)));
        ftfHorFin.setForeground(new java.awt.Color(91, 81, 81));
        ftfHorFin.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getTimeInstance(java.text.DateFormat.SHORT))));
        ftfHorFin.setText("HH:MM (AM/PM)");
        ftfHorFin.setToolTipText("HH:MM en AM/PM");
        ftfHorFin.setSelectedTextColor(new java.awt.Color(253, 255, 246));
        ftfHorFin.setSelectionColor(new java.awt.Color(57, 174, 169));
        ftfHorFin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ftfHorFinMouseClicked(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(229, 239, 193));
        jLabel12.setText("Duración: ");

        txtDuracion.setBackground(new java.awt.Color(229, 239, 193));
        txtDuracion.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtDuracion.setForeground(new java.awt.Color(229, 239, 193));
        txtDuracion.setToolTipText("en minutos");
        txtDuracion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(57, 174, 169)));
        txtDuracion.setSelectedTextColor(new java.awt.Color(253, 255, 246));
        txtDuracion.setSelectionColor(new java.awt.Color(57, 174, 169));
        txtDuracion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDuracionActionPerformed(evt);
            }
        });

        spinCap.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(57, 174, 169)));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(229, 239, 193));
        jLabel13.setText("Disponibilidad: ");

        cbxDisp.setBackground(new java.awt.Color(229, 239, 193));
        cbxDisp.setForeground(new java.awt.Color(91, 81, 81));
        cbxDisp.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Activo", "Terminado" }));
        cbxDisp.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(57, 174, 169)));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(txtDescClase))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel7)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(ftfHorIni, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(jLabel10))
                            .addComponent(ftfFecIni, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(spinCap, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(jLabel13)
                                .addGap(18, 18, 18)
                                .addComponent(cbxDisp, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(ftfHorFin, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ftfFecFin)
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addComponent(jLabel12)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                                        .addComponent(txtDuracion, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addGap(32, 32, 32))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDescClase)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ftfFecIni, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8)
                        .addComponent(ftfFecFin, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel9)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ftfHorIni, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel10)
                    .addComponent(ftfHorFin, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(txtDuracion, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(spinCap, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(cbxDisp, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(106, 106, 106))
        );

        btnAgregarClase.setBackground(new java.awt.Color(32, 101, 98));
        btnAgregarClase.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnAgregarClase.setForeground(new java.awt.Color(229, 239, 193));
        btnAgregarClase.setText("Agregar");
        btnAgregarClase.setBorder(null);
        btnAgregarClase.setBorderPainted(false);
        btnAgregarClase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarClaseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelFondoLayout = new javax.swing.GroupLayout(panelFondo);
        panelFondo.setLayout(panelFondoLayout);
        panelFondoLayout.setHorizontalGroup(
            panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelFondoLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelFondoLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 570, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelFondoLayout.createSequentialGroup()
                        .addGap(220, 220, 220)
                        .addComponent(btnAgregarClase, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        panelFondoLayout.setVerticalGroup(
            panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelFondoLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(btnAgregarClase, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        add(panelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 490));
    }// </editor-fold>//GEN-END:initComponents

    private void txtDuracionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDuracionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDuracionActionPerformed

    private void ftfFecIniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ftfFecIniActionPerformed

    }//GEN-LAST:event_ftfFecIniActionPerformed

    private void ftfFecIniMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ftfFecIniMouseClicked
        ftfFecIni.setText("");
    }//GEN-LAST:event_ftfFecIniMouseClicked

    private void ftfFecFinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ftfFecFinMouseClicked
        ftfFecFin.setText("");
    }//GEN-LAST:event_ftfFecFinMouseClicked

    private void ftfHorFinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ftfHorFinMouseClicked
        ftfHorFin.setText("");
    }//GEN-LAST:event_ftfHorFinMouseClicked

    private void ftfHorIniMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ftfHorIniMouseClicked
        ftfHorIni.setText("");
    }//GEN-LAST:event_ftfHorIniMouseClicked

    private void btnAgregarClaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarClaseActionPerformed
        int i=tblCursos.getSelectedRow(); 
        SimpleDateFormat Dateformatter = new SimpleDateFormat("dd/MM/yyyy");
        SimpleDateFormat Hourformatter = new SimpleDateFormat("HH:mm:ss");
        if(i==-1) return;  //no seleciona nada
        Curso curso=listaCursos.get(i);
        Clase clase =new Clase();
        clase.setDescripcion(txtDescClase.getText());
        clase.setDuracionEnHoras((Integer.parseInt(txtDuracion.getText())));
        try{
            clase.setFechaInicio(Dateformatter.parse(ftfFecIni.getText()));
            clase.setFechaFin(Dateformatter.parse(ftfFecFin.getText()));
            clase.setHoraInicio(Hourformatter.parse(ftfHorIni.getText()));
            clase.setHoraInicio(Hourformatter.parse(ftfHorFin.getText()));

        }catch(ParseException e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnAgregarClaseActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarClase;
    private javax.swing.JComboBox<String> cbxDisp;
    private javax.swing.JFormattedTextField ftfFecFin;
    private javax.swing.JFormattedTextField ftfFecIni;
    private javax.swing.JFormattedTextField ftfHorFin;
    private javax.swing.JFormattedTextField ftfHorIni;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panelFondo;
    private javax.swing.JSpinner spinCap;
    private javax.swing.JTable tblCursos;
    private javax.swing.JTextField txtDescClase;
    private javax.swing.JTextField txtDuracion;
    private javax.swing.JTextField txtIDCurso;
    private javax.swing.JTextField txtNombCurso;
    // End of variables declaration//GEN-END:variables
}
