/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.JButton;

/**
 *
 * @author alulab14
 */
public class ventanaClientes extends javax.swing.JFrame {

    /**
     * Creates new form ventanaClientes
     */
    public ventanaClientes() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    public Image getIconImage(){
	Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("imagenes/icon.png"));
        return retValue;
    }
    
    
    public void setbtnColor(JButton btn){
        btn.setContentAreaFilled(true);
        btn.setForeground(new Color(200,189,187));
        btn.setBackground(new Color(240,240,240));
    }
    
    public void resetbtnColor(JButton btn){
        btn.setContentAreaFilled(false);
        btn.setForeground(new Color(240,240,240));
        btn.setBackground(new Color(200,189,187));
    }
    
    public void resetIcon(JButton btn, String url){
        btn.setIcon(new javax.swing.ImageIcon(getClass().getResource(url))); 
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelMenu = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNombCliente = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        btnInicio = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        btnSalir = new javax.swing.JButton();
        btnInsClase = new javax.swing.JButton();
        btnProdComp = new javax.swing.JButton();
        btnVerPerfil = new javax.swing.JButton();
        panelContent = new javax.swing.JPanel();
        panelAux = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelMenu.setBackground(new java.awt.Color(200, 189, 187));
        panelMenu.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                panelMenuMouseDragged(evt);
            }
        });
        panelMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelMenuMousePressed(evt);
            }
        });

        lblTitulo.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo.setText("GIMNASIO");
        lblTitulo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblTituloMouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(240, 240, 240));
        jLabel2.setText("Cliente");

        txtNombCliente.setEditable(false);
        txtNombCliente.setBackground(new java.awt.Color(200, 189, 187));
        txtNombCliente.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtNombCliente.setForeground(new java.awt.Color(91, 81, 81));
        txtNombCliente.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNombCliente.setText("Nombre del Cliente");
        txtNombCliente.setBorder(null);

        jSeparator1.setBackground(new java.awt.Color(240, 240, 240));
        jSeparator1.setForeground(new java.awt.Color(240, 240, 240));
        jSeparator1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        btnInicio.setBackground(new java.awt.Color(200, 189, 187));
        btnInicio.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnInicio.setForeground(new java.awt.Color(240, 240, 240));
        btnInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/icons/inicio.png"))); // NOI18N
        btnInicio.setText("Inicio");
        btnInicio.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(240, 240, 240)));
        btnInicio.setContentAreaFilled(false);
        btnInicio.setIconTextGap(20);
        btnInicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnInicioMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnInicioMousePressed(evt);
            }
        });
        btnInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInicioActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(143, 120, 116));

        btnSalir.setBackground(new java.awt.Color(143, 120, 116));
        btnSalir.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(200, 189, 187));
        btnSalir.setText("Salir");
        btnSalir.setBorder(null);
        btnSalir.setContentAreaFilled(false);
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        btnInsClase.setBackground(new java.awt.Color(200, 189, 187));
        btnInsClase.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnInsClase.setForeground(new java.awt.Color(240, 240, 240));
        btnInsClase.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/icons/calendar.png"))); // NOI18N
        btnInsClase.setText("Inscribir a Clase");
        btnInsClase.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(240, 240, 240)));
        btnInsClase.setContentAreaFilled(false);
        btnInsClase.setIconTextGap(20);
        btnInsClase.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnInsClaseMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnInsClaseMousePressed(evt);
            }
        });
        btnInsClase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsClaseActionPerformed(evt);
            }
        });

        btnProdComp.setBackground(new java.awt.Color(200, 189, 187));
        btnProdComp.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnProdComp.setForeground(new java.awt.Color(240, 240, 240));
        btnProdComp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/icons/shopping-cart.png"))); // NOI18N
        btnProdComp.setText("Productos Comprados");
        btnProdComp.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(240, 240, 240)));
        btnProdComp.setContentAreaFilled(false);
        btnProdComp.setIconTextGap(20);
        btnProdComp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnProdCompMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnProdCompMousePressed(evt);
            }
        });
        btnProdComp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProdCompActionPerformed(evt);
            }
        });

        btnVerPerfil.setBackground(new java.awt.Color(200, 189, 187));
        btnVerPerfil.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnVerPerfil.setForeground(new java.awt.Color(240, 240, 240));
        btnVerPerfil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/icons/cliente.png"))); // NOI18N
        btnVerPerfil.setText("Perfil");
        btnVerPerfil.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(240, 240, 240)));
        btnVerPerfil.setContentAreaFilled(false);
        btnVerPerfil.setIconTextGap(20);
        btnVerPerfil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVerPerfilMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnVerPerfilMousePressed(evt);
            }
        });
        btnVerPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerPerfilActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelMenuLayout = new javax.swing.GroupLayout(panelMenu);
        panelMenu.setLayout(panelMenuLayout);
        panelMenuLayout.setHorizontalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenuLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(panelMenuLayout.createSequentialGroup()
                .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelMenuLayout.createSequentialGroup()
                        .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelMenuLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(panelMenuLayout.createSequentialGroup()
                                        .addGap(12, 12, 12)
                                        .addComponent(lblTitulo))))
                            .addGroup(panelMenuLayout.createSequentialGroup()
                                .addGap(97, 97, 97)
                                .addComponent(jLabel2))
                            .addGroup(panelMenuLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(txtNombCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMenuLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnVerPerfil, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnProdComp, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnInsClase, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                            .addComponent(btnInicio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        panelMenuLayout.setVerticalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenuLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(lblTitulo)
                .addGap(2, 2, 2)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtNombCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addComponent(btnInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnVerPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnInsClase, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnProdComp, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(panelMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, 490));

        panelContent.setBackground(new java.awt.Color(117, 126, 131));

        panelAux.setBackground(new java.awt.Color(117, 126, 131));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/icons/client(1).png"))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(240, 240, 240));
        jLabel4.setText("Bienvenido al sistema de clientes de GIMNASIO");

        javax.swing.GroupLayout panelAuxLayout = new javax.swing.GroupLayout(panelAux);
        panelAux.setLayout(panelAuxLayout);
        panelAuxLayout.setHorizontalGroup(
            panelAuxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAuxLayout.createSequentialGroup()
                .addContainerGap(52, Short.MAX_VALUE)
                .addGroup(panelAuxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAuxLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(46, 46, 46))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAuxLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(122, 122, 122))))
        );
        panelAuxLayout.setVerticalGroup(
            panelAuxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAuxLayout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addContainerGap(104, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelContentLayout = new javax.swing.GroupLayout(panelContent);
        panelContent.setLayout(panelContentLayout);
        panelContentLayout.setHorizontalGroup(
            panelContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelAux, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelContentLayout.setVerticalGroup(
            panelContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelAux, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(panelContent, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, 610, 490));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    int xx;
    int xy;
    
    private void btnInicioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInicioMouseClicked

    }//GEN-LAST:event_btnInicioMouseClicked

    private void btnInicioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInicioMousePressed

    }//GEN-LAST:event_btnInicioMousePressed

    private void btnInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicioActionPerformed
        setbtnColor(btnInicio);
        resetbtnColor(btnVerPerfil);
        resetbtnColor(btnInsClase);
        resetbtnColor(btnProdComp);
        btnInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/icons/inicio(1).png"))); 
        resetIcon(btnVerPerfil, "/vista/icons/cliente.png");
        resetIcon(btnInsClase, "/vista/icons/calendar.png");
        resetIcon(btnProdComp, "/vista/icons/shopping-cart.png");
        
        panelContent.removeAll();
        panelContent.add(panelAux,BorderLayout.CENTER);
        panelContent.revalidate();
        panelContent.repaint();
    }//GEN-LAST:event_btnInicioActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnInsClaseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInsClaseMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnInsClaseMouseClicked

    private void btnInsClaseMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInsClaseMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnInsClaseMousePressed

    private void btnInsClaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsClaseActionPerformed
        setbtnColor(btnInsClase);
        resetbtnColor(btnVerPerfil);
        resetbtnColor(btnInicio);
        resetbtnColor(btnProdComp);
        btnInsClase.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/icons/calendar (1).png"))); 
        resetIcon(btnVerPerfil, "/vista/icons/cliente.png");
        resetIcon(btnInicio, "/vista/icons/inicio.png");
        resetIcon(btnProdComp, "/vista/icons/shopping-cart.png");
        
        Vcliente_inscribirClase panelInscribirClase = new Vcliente_inscribirClase();
        panelInscribirClase.setSize(610, 490); 
        panelInscribirClase.setLocation(0, 0); 

        panelContent.removeAll();
        panelContent.add(panelInscribirClase, BorderLayout.CENTER);
        panelContent.revalidate();
        panelContent.repaint();
    }//GEN-LAST:event_btnInsClaseActionPerformed

    private void btnProdCompMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProdCompMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnProdCompMouseClicked

    private void btnProdCompMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProdCompMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnProdCompMousePressed

    private void btnProdCompActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProdCompActionPerformed
        setbtnColor(btnProdComp);
        resetbtnColor(btnVerPerfil);
        resetbtnColor(btnInicio);
        resetbtnColor(btnInsClase);
        btnProdComp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/icons/shopping-cart (1).png"))); 
        resetIcon(btnVerPerfil, "/vista/icons/cliente.png");
        resetIcon(btnInicio, "/vista/icons/inicio.png");
        resetIcon(btnInsClase, "/vista/icons/calendar.png");
        
        Vcliente_ProductosComprados panelProdComp = new Vcliente_ProductosComprados();
        panelProdComp.setSize(610, 490); 
        panelProdComp.setLocation(0, 0); 

        panelContent.removeAll();
        panelContent.add(panelProdComp, BorderLayout.CENTER);
        panelContent.revalidate();
        panelContent.repaint();
    }//GEN-LAST:event_btnProdCompActionPerformed

    private void btnVerPerfilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVerPerfilMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVerPerfilMouseClicked

    private void btnVerPerfilMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVerPerfilMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVerPerfilMousePressed

    private void btnVerPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerPerfilActionPerformed
        setbtnColor(btnVerPerfil);
        resetbtnColor(btnInicio);
        resetbtnColor(btnInsClase);
        resetbtnColor(btnProdComp);
        btnVerPerfil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/icons/cliente(1).png"))); 
        resetIcon(btnInicio, "/vista/icons/inicio.png");
        resetIcon(btnInsClase, "/vista/icons/calendar.png");
        resetIcon(btnProdComp, "/vista/icons/shopping-cart.png");
        
        Vcliente_perfil panelPerfilCli = new Vcliente_perfil();
        panelPerfilCli.setSize(610, 490); 
        panelPerfilCli.setLocation(0, 0); 

        panelContent.removeAll();
        panelContent.add(panelPerfilCli, BorderLayout.CENTER);
        panelContent.revalidate();
        panelContent.repaint();
    }//GEN-LAST:event_btnVerPerfilActionPerformed

    private void panelMenuMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelMenuMousePressed
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_panelMenuMousePressed

    private void panelMenuMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelMenuMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xx, y - xy);
    }//GEN-LAST:event_panelMenuMouseDragged

    private void lblTituloMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTituloMouseClicked
        panelContent.removeAll();
        panelContent.add(panelAux,BorderLayout.CENTER);
        panelContent.revalidate();
        panelContent.repaint();
        
        resetbtnColor(btnVerPerfil);
        resetbtnColor(btnInicio);
        resetbtnColor(btnInsClase);
        resetbtnColor(btnProdComp);
        
        resetIcon(btnVerPerfil, "/vista/icons/cliente.png");
        resetIcon(btnInicio, "/vista/icons/inicio.png");
        resetIcon(btnInsClase,"/vista/icons/calendar.png");
        resetIcon(btnProdComp,"/vista/icons/shopping-cart.png");
    }//GEN-LAST:event_lblTituloMouseClicked
                                    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows Classic".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ventanaClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ventanaClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ventanaClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ventanaClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ventanaClientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInicio;
    private javax.swing.JButton btnInsClase;
    private javax.swing.JButton btnProdComp;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnVerPerfil;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel panelAux;
    private javax.swing.JPanel panelContent;
    private javax.swing.JPanel panelMenu;
    private javax.swing.JTextField txtNombCliente;
    // End of variables declaration//GEN-END:variables
}
