/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.AutenticacionControlador;
import controlador.EntrenadorControlador;
import java.awt.event.ActionListener;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import vista.interfaces.IVista;
import java.awt.Image;
import java.awt.Toolkit;
/**
 *
 * @author pseudocfoch
 */
public class VentanaAutenticacion extends javax.swing.JFrame implements IVista {
    AutenticacionControlador controlador;
    public static final class Action {
        public static final String ENTRAR_CLICKED = "entrar_clicked";
    }
    /**
     * Creates new form VentanaLogin
     */
    public VentanaAutenticacion() {
        initComponents();
        this.setLocationRelativeTo(null);
        controlador = null;
    }
    
    public Image getIconImage(){
	Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("imagenes/icon.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        loginLabel = new javax.swing.JLabel();
        loginTextField = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        contrasenaLabel = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        contrasenaPasswordField = new javax.swing.JPasswordField();
        entrarButton = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        img = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(14, 56, 103));
        setIconImage(getIconImage());
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(94, 88, 78));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(431, 450));
        jPanel1.setMinimumSize(new java.awt.Dimension(431, 450));

        loginLabel.setFont(new java.awt.Font("Source Sans Pro ExtraLight", 0, 18)); // NOI18N
        loginLabel.setForeground(new java.awt.Color(255, 255, 255));
        loginLabel.setText("DNI o ID:");

        loginTextField.setBackground(new java.awt.Color(94, 88, 78));
        loginTextField.setFont(new java.awt.Font("Source Sans Pro Light", 0, 14)); // NOI18N
        loginTextField.setForeground(new java.awt.Color(255, 255, 255));
        loginTextField.setText("Ingresa tu DNI o ID de usuario");
        loginTextField.setBorder(null);
        loginTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginTextFieldMouseClicked(evt);
            }
        });
        loginTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginTextFieldActionPerformed(evt);
            }
        });

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));

        jLabel4.setFont(new java.awt.Font("Source Code Pro Light", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Gimnasio");

        contrasenaLabel.setFont(new java.awt.Font("Source Sans Pro ExtraLight", 0, 18)); // NOI18N
        contrasenaLabel.setForeground(new java.awt.Color(255, 255, 255));
        contrasenaLabel.setText("Contraseña:");

        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));

        contrasenaPasswordField.setBackground(new java.awt.Color(94, 88, 78));
        contrasenaPasswordField.setFont(new java.awt.Font("Source Code Pro ExtraLight", 0, 14)); // NOI18N
        contrasenaPasswordField.setForeground(new java.awt.Color(255, 255, 255));
        contrasenaPasswordField.setText("jPasswordField1");
        contrasenaPasswordField.setBorder(null);
        contrasenaPasswordField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                contrasenaPasswordFieldMouseClicked(evt);
            }
        });

        entrarButton.setBackground(new java.awt.Color(156, 148, 137));
        entrarButton.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        entrarButton.setForeground(new java.awt.Color(94, 88, 78));
        entrarButton.setText("Entrar");
        entrarButton.setBorder(null);
        entrarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entrarButtonActionPerformed(evt);
            }
        });

        btnSalir.setBackground(new java.awt.Color(156, 148, 137));
        btnSalir.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(94, 88, 78));
        btnSalir.setText("X");
        btnSalir.setBorderPainted(false);
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(img)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(jLabel4))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                .addComponent(entrarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(contrasenaPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(contrasenaLabel)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(loginTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(loginLabel)
                                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSalir)
                .addGap(22, 22, 22))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(img)
                .addGap(20, 20, 20)
                .addComponent(btnSalir)
                .addGap(16, 16, 16)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(loginLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(loginTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(contrasenaLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(contrasenaPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(entrarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, 435));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loginTextFieldActionPerformed

    private void entrarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entrarButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_entrarButtonActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void loginTextFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginTextFieldMouseClicked
        loginTextField.setText("");
    }//GEN-LAST:event_loginTextFieldMouseClicked

    private void contrasenaPasswordFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_contrasenaPasswordFieldMouseClicked
        contrasenaPasswordField.setText("");
    }//GEN-LAST:event_contrasenaPasswordFieldMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaAutenticacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaAutenticacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaAutenticacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaAutenticacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaAutenticacion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel contrasenaLabel;
    private javax.swing.JPasswordField contrasenaPasswordField;
    private javax.swing.JButton entrarButton;
    private javax.swing.JLabel img;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel loginLabel;
    private javax.swing.JTextField loginTextField;
    // End of variables declaration//GEN-END:variables

    @Override
    public void agregarControlador(ActionListener controlador) {
        this.controlador = (AutenticacionControlador) controlador;
        this.entrarButton.addActionListener(controlador);
        this.entrarButton.setActionCommand(Action.ENTRAR_CLICKED);
    }
    
    public Integer getLogin() {
        Integer login;
        try {
            login = Integer.parseInt(this.loginTextField.getText());
        } catch (NumberFormatException exception) {
            login = -1;
        }
        return login;
    }
    
    public String getConstrasena() {
        return String.valueOf(this.contrasenaPasswordField.getPassword());
    }
    
    public void mostrarDialogoError() {
        JFrame frame;
        frame = new JFrame();
        JOptionPane.showMessageDialog(frame, "Datos invalidos",
                "Error de autenticación", JOptionPane.ERROR_MESSAGE);
        // TODO
        // Creo que esto ya no es necesario.
        controlador.setEsperando(false);        
    }
    
    public void mostrarDialogoExito() {
        Object[] options = { "Entrar" };
        JFrame frame;
        int res;
        
        frame = new JFrame();        
        res = JOptionPane.showOptionDialog(frame,
                "La autenticación ha sido satisfactoria",
                "Autenticación correcta", JOptionPane.PLAIN_MESSAGE,
                JOptionPane.QUESTION_MESSAGE, null, options, options[0]);
        
        if (res == JOptionPane.OK_OPTION) {
            EntrenadorControlador entrenadorControlador;
 
            //VentanaPrincipal ventanaPrincipal;
            VentanaEntrenador ventanaPrincipal;
            // TODO
            // Falta un controlador para la ventana principal que reciba como
            // argumento una Persona, asi podemos manejar los permisos de la
            // persona segun su jerarquia
            ventanaPrincipal = new VentanaEntrenador();
            entrenadorControlador = new EntrenadorControlador(ventanaPrincipal,
                    this.controlador.getEntrenador());
            ventanaPrincipal.agregarControlador(entrenadorControlador);
            ventanaPrincipal.setVisible(true);
            this.setVisible(false);
        }
        // TODO
        // Creo que esto ya no es necesario.
        controlador.setEsperando(false);
    }
}
