/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;


import controlador.EntrenadorPerfilControlador;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.event.ActionListener;
import modelo.Entrenador;
import vista.interfaces.IVista;

/**
 *
 * @author Lin
 */
public class Ventrenador_perfil extends javax.swing.JPanel implements IVista {

    private EntrenadorPerfilControlador controlador;

    /**
     * Creates new form entrenador_perfil
     */
    public Ventrenador_perfil() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPerfil = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtEstLab = new javax.swing.JTextField();
        txtSueldo = new javax.swing.JTextField();
        txtTurno = new javax.swing.JTextField();
        txtClientDisp = new javax.swing.JTextField();
        txtMaxCli = new javax.swing.JTextField();
        txtEsp = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtTel = new javax.swing.JTextField();
        txtCuentaBancaria = new javax.swing.JTextField();
        txtNomb = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtDNI = new javax.swing.JTextField();
        btnModPerfil = new javax.swing.JButton();

        setBackground(new java.awt.Color(85, 123, 131));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelPerfil.setBackground(new java.awt.Color(85, 123, 131));

        jPanel1.setBackground(new java.awt.Color(85, 123, 131));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Información de Trabajo", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(229, 239, 193))); // NOI18N
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setForeground(new java.awt.Color(229, 239, 193));
        jLabel1.setText("Estado Laboral: ");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 45, -1, -1));

        jLabel2.setForeground(new java.awt.Color(229, 239, 193));
        jLabel2.setText("Sueldo(S/.) : ");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 77, -1, -1));

        jLabel3.setForeground(new java.awt.Color(229, 239, 193));
        jLabel3.setText("Turno: ");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(249, 78, -1, -1));

        jLabel4.setForeground(new java.awt.Color(229, 239, 193));
        jLabel4.setText("Especialidad: ");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(249, 45, -1, -1));

        jLabel10.setForeground(new java.awt.Color(229, 239, 193));
        jLabel10.setText("Cantidad Máxima Clientes: ");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 111, -1, -1));

        jLabel11.setForeground(new java.awt.Color(229, 239, 193));
        jLabel11.setText("Cantidad Clientes Disponibles:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(249, 111, -1, -1));

        txtEstLab.setEditable(false);
        txtEstLab.setBackground(new java.awt.Color(85, 123, 131));
        txtEstLab.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtEstLab.setForeground(new java.awt.Color(162, 213, 171));
        txtEstLab.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        txtEstLab.setText("Activo");
        txtEstLab.setBorder(null);
        txtEstLab.setSelectedTextColor(new java.awt.Color(253, 255, 246));
        txtEstLab.setSelectionColor(new java.awt.Color(162, 213, 171));
        jPanel1.add(txtEstLab, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 44, 82, -1));

        txtSueldo.setEditable(false);
        txtSueldo.setBackground(new java.awt.Color(85, 123, 131));
        txtSueldo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtSueldo.setForeground(new java.awt.Color(162, 213, 171));
        txtSueldo.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        txtSueldo.setText("3000");
        txtSueldo.setBorder(null);
        txtSueldo.setSelectedTextColor(new java.awt.Color(253, 255, 246));
        txtSueldo.setSelectionColor(new java.awt.Color(162, 213, 171));
        jPanel1.add(txtSueldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 77, 82, -1));

        txtTurno.setEditable(false);
        txtTurno.setBackground(new java.awt.Color(85, 123, 131));
        txtTurno.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtTurno.setForeground(new java.awt.Color(162, 213, 171));
        txtTurno.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        txtTurno.setText("Matutino");
        txtTurno.setBorder(null);
        txtTurno.setSelectedTextColor(new java.awt.Color(253, 255, 246));
        txtTurno.setSelectionColor(new java.awt.Color(162, 213, 171));
        jPanel1.add(txtTurno, new org.netbeans.lib.awtextra.AbsoluteConstraints(381, 77, 133, -1));

        txtClientDisp.setEditable(false);
        txtClientDisp.setBackground(new java.awt.Color(85, 123, 131));
        txtClientDisp.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtClientDisp.setForeground(new java.awt.Color(162, 213, 171));
        txtClientDisp.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        txtClientDisp.setText("20");
        txtClientDisp.setBorder(null);
        txtClientDisp.setSelectedTextColor(new java.awt.Color(253, 255, 246));
        txtClientDisp.setSelectionColor(new java.awt.Color(162, 213, 171));
        jPanel1.add(txtClientDisp, new org.netbeans.lib.awtextra.AbsoluteConstraints(442, 110, 72, -1));

        txtMaxCli.setEditable(false);
        txtMaxCli.setBackground(new java.awt.Color(85, 123, 131));
        txtMaxCli.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtMaxCli.setForeground(new java.awt.Color(162, 213, 171));
        txtMaxCli.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        txtMaxCli.setText("20");
        txtMaxCli.setBorder(null);
        txtMaxCli.setSelectedTextColor(new java.awt.Color(253, 255, 246));
        txtMaxCli.setSelectionColor(new java.awt.Color(162, 213, 171));
        jPanel1.add(txtMaxCli, new org.netbeans.lib.awtextra.AbsoluteConstraints(166, 110, 56, -1));

        txtEsp.setEditable(false);
        txtEsp.setBackground(new java.awt.Color(85, 123, 131));
        txtEsp.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtEsp.setForeground(new java.awt.Color(162, 213, 171));
        txtEsp.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        txtEsp.setText("Levantamiento de Pesas");
        txtEsp.setBorder(null);
        txtEsp.setSelectedTextColor(new java.awt.Color(253, 255, 246));
        txtEsp.setSelectionColor(new java.awt.Color(162, 213, 171));
        jPanel1.add(txtEsp, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 40, -1, -1));

        jPanel2.setBackground(new java.awt.Color(85, 123, 131));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos Personales", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(229, 239, 193))); // NOI18N
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setForeground(new java.awt.Color(229, 239, 193));
        jLabel5.setText("DNI:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(148, 46, -1, -1));

        jLabel6.setForeground(new java.awt.Color(229, 239, 193));
        jLabel6.setText("Nombres: ");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(148, 72, -1, -1));

        jLabel7.setForeground(new java.awt.Color(229, 239, 193));
        jLabel7.setText("E-mail: ");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(148, 98, -1, -1));

        jLabel8.setForeground(new java.awt.Color(229, 239, 193));
        jLabel8.setText("Teléfono: ");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(148, 124, -1, -1));

        jLabel9.setForeground(new java.awt.Color(229, 239, 193));
        jLabel9.setText("Cuenta Bancaria: ");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(148, 150, -1, -1));

        txtTel.setEditable(false);
        txtTel.setBackground(new java.awt.Color(85, 123, 131));
        txtTel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtTel.setForeground(new java.awt.Color(162, 213, 171));
        txtTel.setText("XXXX-XXXX-XXXX-XXXX");
        txtTel.setBorder(null);
        txtTel.setSelectedTextColor(new java.awt.Color(253, 255, 246));
        txtTel.setSelectionColor(new java.awt.Color(162, 213, 171));
        jPanel2.add(txtTel, new org.netbeans.lib.awtextra.AbsoluteConstraints(269, 123, 221, -1));

        txtCuentaBancaria.setEditable(false);
        txtCuentaBancaria.setBackground(new java.awt.Color(85, 123, 131));
        txtCuentaBancaria.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtCuentaBancaria.setForeground(new java.awt.Color(162, 213, 171));
        txtCuentaBancaria.setText("XXXX-XXXX-XXXX-XXXX");
        txtCuentaBancaria.setBorder(null);
        txtCuentaBancaria.setSelectedTextColor(new java.awt.Color(253, 255, 246));
        txtCuentaBancaria.setSelectionColor(new java.awt.Color(162, 213, 171));
        jPanel2.add(txtCuentaBancaria, new org.netbeans.lib.awtextra.AbsoluteConstraints(269, 149, 221, -1));

        txtNomb.setEditable(false);
        txtNomb.setBackground(new java.awt.Color(85, 123, 131));
        txtNomb.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtNomb.setForeground(new java.awt.Color(162, 213, 171));
        txtNomb.setText("XXXX-XXXX-XXXX-XXXX");
        txtNomb.setBorder(null);
        txtNomb.setSelectedTextColor(new java.awt.Color(253, 255, 246));
        txtNomb.setSelectionColor(new java.awt.Color(162, 213, 171));
        jPanel2.add(txtNomb, new org.netbeans.lib.awtextra.AbsoluteConstraints(269, 71, 221, -1));

        txtEmail.setEditable(false);
        txtEmail.setBackground(new java.awt.Color(85, 123, 131));
        txtEmail.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtEmail.setForeground(new java.awt.Color(162, 213, 171));
        txtEmail.setText("XXXX-XXXX-XXXX-XXXX");
        txtEmail.setBorder(null);
        txtEmail.setSelectedTextColor(new java.awt.Color(253, 255, 246));
        txtEmail.setSelectionColor(new java.awt.Color(162, 213, 171));
        jPanel2.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(269, 97, 221, -1));

        txtDNI.setEditable(false);
        txtDNI.setBackground(new java.awt.Color(85, 123, 131));
        txtDNI.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtDNI.setForeground(new java.awt.Color(162, 213, 171));
        txtDNI.setText("XXXX-XXXX-XXXX-XXXX");
        txtDNI.setBorder(null);
        txtDNI.setSelectedTextColor(new java.awt.Color(253, 255, 246));
        txtDNI.setSelectionColor(new java.awt.Color(162, 213, 171));
        jPanel2.add(txtDNI, new org.netbeans.lib.awtextra.AbsoluteConstraints(269, 45, 221, -1));

        btnModPerfil.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnModPerfil.setForeground(new java.awt.Color(229, 239, 193));
        btnModPerfil.setText("<html><u>Modificar Perfil</u><html>");
        btnModPerfil.setBorder(null);
        btnModPerfil.setContentAreaFilled(false);
        btnModPerfil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnModPerfilMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnModPerfilMouseReleased(evt);
            }
        });
        btnModPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModPerfilActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelPerfilLayout = new javax.swing.GroupLayout(panelPerfil);
        panelPerfil.setLayout(panelPerfilLayout);
        panelPerfilLayout.setHorizontalGroup(
            panelPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPerfilLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(panelPerfilLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(panelPerfilLayout.createSequentialGroup()
                .addGap(440, 440, 440)
                .addComponent(btnModPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panelPerfilLayout.setVerticalGroup(
            panelPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPerfilLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(btnModPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        add(panelPerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 490));
    }// </editor-fold>//GEN-END:initComponents

    private void btnModPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModPerfilActionPerformed
        

        VentrenadorModPerfil ventModPerfil = new VentrenadorModPerfil();
        ventModPerfil.setSize(610, 490);
        ventModPerfil.setLocation(0, 0);

        panelPerfil.removeAll();
        panelPerfil.add(ventModPerfil, BorderLayout.CENTER);
        panelPerfil.revalidate();
        panelPerfil.repaint();
    }//GEN-LAST:event_btnModPerfilActionPerformed

    private void btnModPerfilMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnModPerfilMousePressed
        btnModPerfil.setForeground(new Color(162, 213, 171));
    }//GEN-LAST:event_btnModPerfilMousePressed

    private void btnModPerfilMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnModPerfilMouseReleased
        btnModPerfil.setForeground(new Color(229, 239, 193));
    }//GEN-LAST:event_btnModPerfilMouseReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnModPerfil;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel panelPerfil;
    private javax.swing.JTextField txtClientDisp;
    private javax.swing.JTextField txtCuentaBancaria;
    private javax.swing.JTextField txtDNI;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtEsp;
    private javax.swing.JTextField txtEstLab;
    private javax.swing.JTextField txtMaxCli;
    private javax.swing.JTextField txtNomb;
    private javax.swing.JTextField txtSueldo;
    private javax.swing.JTextField txtTel;
    private javax.swing.JTextField txtTurno;
    // End of variables declaration//GEN-END:variables

    public void setPerfil(Entrenador entrenador) {
        this.txtDNI.setText(Integer.toString(entrenador.getDni()));
        this.txtCuentaBancaria.setText(entrenador.getCuentaBancaria());
        this.txtEmail.setText(entrenador.getEmail());
        this.txtEsp.setText(entrenador.getEspecialidad());
        this.txtEstLab.setText(entrenador.getEstadoLaboral());
        this.txtMaxCli.setText(Integer.toString(entrenador.getCantidadMaximaClientes()));
        this.txtNomb.setText(entrenador.getNombre());
        this.txtSueldo.setText(Double.toString(entrenador.getSueldo()));
        this.txtTel.setText(entrenador.getTelefono());
        this.txtTurno.setText(entrenador.getTurno().getNombreTurno());
    }

    @Override
    public void agregarControlador(ActionListener controlador) {
        this.controlador = (EntrenadorPerfilControlador) controlador;
        setPerfil(this.controlador.getEntrenador());
    }

}
