/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;
import controlador.EntrenadorControlador;
import java.awt.event.ActionListener;
import vista.interfaces.IVista;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author pseudocfoch
 */
public class VentanaEntrenador extends javax.swing.JInternalFrame implements IVista {
    public static final class Action {
        public static final String REFRESCAR_BUTTON_CLICKED = "refrescar_button_clicked";
    }
    
    DefaultTableModel modelo;
    EntrenadorControlador controlador;
    
    /**
     * Creates new form VentanaEntrenador
     */
    public VentanaEntrenador() {
        initComponents();
        String cabecera[] = {"DNI", "Nombre", "Apellido paterno",
            "Apellido Materno", "Sueldo"};
        String datos[][] = {};
        modelo = new DefaultTableModel(datos, cabecera);
        this.entrenadorTable.setModel(modelo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        entrenadorTable = new javax.swing.JTable();
        refrescarButton = new javax.swing.JButton();

        setTitle("Entrenadores");

        entrenadorTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(entrenadorTable);

        refrescarButton.setText("Refrescar");
        refrescarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refrescarButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 591, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(refrescarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(refrescarButton)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void refrescarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refrescarButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_refrescarButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable entrenadorTable;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton refrescarButton;
    // End of variables declaration//GEN-END:variables

    @Override
    public void agregarControlador(ActionListener controlador) {
        this.controlador = (EntrenadorControlador) controlador;
        this.refrescarButton.addActionListener(controlador);
        this.refrescarButton.setActionCommand(Action.REFRESCAR_BUTTON_CLICKED);
    }
    
    public void agregarDatos(Object [] datos) {
        this.modelo.addRow(datos);
    }
    
    public void borrar() {
        int i;
        for (i = this.modelo.getRowCount() - 1; i >= 0; i--) {
            this.modelo.removeRow(i);
        }
    }
}
